"""Live walk-forward adjudication of the registered funding-regime hypothesis.

PR #64's finding: the cross-sectional funding-carry factor is regime-
dependent -- three negative quarters, a transition, then four consecutive
positive quarters (+0.029 IC each) from 2025-Q3 onward. The hypothesis
"since mid-2025, high-funding contracts outperform" was generated BY that
history, so no amount of re-analysis of the same history can test it. Only
data that did not exist yet can.

This service is that test, running unattended:

* Every cycle it pulls recent funding rates and 8h closes for every USDT
  perpetual TRADING at that moment (point-in-time by construction -- the
  universe is whatever is listed when the observation is made).
* For each 8h stamp whose 24h forward window has closed, it computes the
  cross-sectional Spearman IC of ``+funding_carry_24h`` -- trailing 3-stamp
  mean funding, high funding scored HIGH, the exact registered sign -- against
  the demeaned 24h forward return.
* Each resolved stamp is INSERTED ONCE and never recomputed. Recomputing
  history from a later listing set would drop contracts delisted in the
  interim, quietly reintroducing survivorship bias into the adjudication
  record itself.

The registered bar (GO_LIVE.md, 2026-07-31): FOUR consecutive calendar
quarters of positive mean IC on unseen data (2026-Q3 onward) before any
trading proposal may cite this factor. The watch has no opinion; it counts.

This is research telemetry only: nothing here places orders, feeds the
optimizer, or touches account state.
"""

from __future__ import annotations

import asyncio
from dataclasses import dataclass
from datetime import UTC, datetime
from typing import Any, Protocol

import numpy as np
import structlog
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from core.models.research import FactorWatchObservation

logger = structlog.get_logger(__name__)

FACTOR_NAME = "funding_carry_24h_plus"
HORIZON_STAMPS = 3  # 3 x 8h = 24h, as registered
CARRY_LOOKBACK_STAMPS = 3
# Registration boundary: data before this was seen by the study that
# generated the hypothesis, so it can never count toward adjudication.
UNSEEN_FROM = datetime(2026, 7, 1, tzinfo=UTC)
_MS_8H = 8 * 3_600_000
_MS_4H = 4 * 3_600_000
_MIN_SYMBOLS = 20
# One cycle per 8h stamp, with slack for fetch time.
_CYCLE_SECONDS = 8 * 3600.0
# ~45 days of stamps per fetch: the deepest factor lookback
# (trend_follow_30d: 90 stamps) plus the horizon plus a FULL
# _MAX_HEAL_DAYS of healing slack for every factor. Widened with the
# 2026-08-29 registration (amended 100 -> 136 in review so the 30d factor
# is not the only one with ~56h of slack); per-factor boundaries and the
# append-only dedup are window-independent.
_FETCH_STAMPS = 136
# An observation may be INSERTED at most this many days after its stamp.
# The window widening is for LOOKBACK data, not stale insertion: a stamp
# first computed a month late would be scored on the CURRENT listing set
# (contracts delisted in the interim silently absent -- survivorship), and
# near the /futures/data ~30-day retention edge the extras can be finite
# for an alphabetical PREFIX of the universe only. Past this cap a gap
# stays a visible gap, never a quietly biased row (review, 2026-08-29).
_MAX_HEAL_DAYS = 14
# The /futures/data/* family has its OWN limit -- 1,000 requests per 5
# minutes per IP -- which ccxt's weight-based throttler does not model.
# Self-imposed spacing keeps the family under ~860/5min; a violation
# escalates to an IP ban that would hit the live trading stack.
_DATA_FAMILY_MIN_INTERVAL_S = 0.35
# If more than this fraction of a series' per-symbol requests ERROR in a
# cycle, the whole series is dropped for the cycle: a mid-loop failure
# (rate limiting, partial outage) would otherwise leave an alphabetical
# PREFIX of the universe in the matrix, and a cross-sectional IC on a
# biased sub-universe would be permanently recorded as if it were the
# registered one. Thin/absent data for a symbol is NOT an error.
_MAX_SERIES_ERROR_FRACTION = 0.10


@dataclass(frozen=True)
class WatchedFactor:
    """One registered hypothesis under live adjudication.

    ``unseen_from`` is each factor's own registration boundary: stamps before
    it were visible to the study that generated the hypothesis and can never
    count toward its adjudication. ``min_history`` stamps of data must exist
    behind a stamp before its signal is scored. ``requires`` names the extra
    data series (beyond close/funding/volume) the builder needs; when any is
    unavailable in a cycle the factor is skipped, never fed garbage.
    """

    name: str
    unseen_from: datetime
    min_history: int
    build: SignalBuilder | ExtendedSignalBuilder
    requires: tuple[str, ...] = ()


class SignalBuilder(Protocol):
    def __call__(
        self, close: np.ndarray, funding: np.ndarray, volume: np.ndarray
    ) -> np.ndarray: ...


class ExtendedSignalBuilder(Protocol):
    def __call__(
        self,
        close: np.ndarray,
        funding: np.ndarray,
        volume: np.ndarray,
        extras: dict[str, np.ndarray],
    ) -> np.ndarray: ...


def _parse_boundary_snapshots(rows: list[dict], field: str) -> dict[int, float]:
    """Snapshot series: keep points whose timestamp is exactly ON the 8h
    grid -- the value AT the stamp, nothing floored or filled forward
    (flooring would pull intra-bucket future data backward)."""
    out: dict[int, float] = {}
    for row in rows:
        try:
            ts = int(row["timestamp"])
            if ts % _MS_8H == 0:
                out[ts] = float(row[field])
        except (KeyError, TypeError, ValueError):
            continue
    return out


def _parse_taker_8h(rows: list[dict]) -> dict[int, float]:
    """Taker flow: compose each full 8h-period buy/sell ratio from its two
    4h halves (period-START stamping, verified empirically 2026-08-09: the
    1d aggregate equals the sum of the 4h points stamped from the same
    instant forward). A stamp missing either half stays absent -- a
    half-window ratio is a different variable than the registered one."""
    vols: dict[int, tuple[float, float]] = {}
    for row in rows:
        try:
            vols[int(row["timestamp"])] = (float(row["buyVol"]), float(row["sellVol"]))
        except (KeyError, TypeError, ValueError):
            continue
    out: dict[int, float] = {}
    for ts, (buy1, sell1) in vols.items():
        if ts % _MS_8H != 0:
            continue
        second = vols.get(ts + _MS_4H)
        if second is None:
            continue
        buy, sell = buy1 + second[0], sell1 + second[1]
        if sell > 0:
            out[ts] = buy / sell
    return out


# The orthogonal data series (registered 2026-08-09): public Binance futures
# data endpoints, mapped as series name -> (ccxt implicit method, parser).
# All three endpoints serve 4h periods (no 8h option); each parser produces
# {8h stamp: value} under the causality rules fixed in the registration.
_EXTRA_SERIES: dict[str, tuple[str, Any]] = {
    "open_interest": (
        "fapiDataGetOpenInterestHist",
        lambda rows: _parse_boundary_snapshots(rows, "sumOpenInterest"),
    ),
    "global_long_short": (
        "fapiDataGetGlobalLongShortAccountRatio",
        lambda rows: _parse_boundary_snapshots(rows, "longShortRatio"),
    ),
    "taker_buy_ratio": ("fapiDataGetTakerlongshortRatio", _parse_taker_8h),
}


def _closed_bars(bars: list, now_ms: int) -> dict[int, tuple[float, float]]:
    """Kline rows -> {8h open-time stamp: (close, volume)}, EXCLUDING any bar
    still open at *now_ms*.

    Binance includes the in-progress candle in fetch_ohlcv, and before the
    2026-08-09 review fix its live mid-bar price could become a permanently
    recorded IC exit -- shortening the registered 24h window to 16h+drift.
    An exit price must be a settled close or the stamp must wait a cycle.
    """
    out: dict[int, tuple[float, float]] = {}
    for b in bars:
        stamp = (int(b[0]) // _MS_8H) * _MS_8H
        if stamp + _MS_8H <= now_ms:
            out[stamp] = (float(b[4]), float(b[5]))
    return out


def _blank_ragged_retention_edge(extras: dict[str, np.ndarray]) -> None:
    """NaN out each extras series' OLDEST populated grid row, in place.

    The /futures/data endpoints retain ~30 days, and the per-symbol fetch
    loop takes minutes: if the retention window advances mid-loop, the
    oldest available stamp exists for an alphabetical prefix of symbols
    only. That row can never be told apart from honest thin data, so it is
    never scored; the cost is one ~30-day-old stamp per series per cycle.
    """
    for matrix in extras.values():
        finite_rows = np.where(np.isfinite(matrix).any(axis=1))[0]
        if finite_rows.size:
            matrix[finite_rows[0]] = np.nan


def _series_is_trustworthy(attempts: int, errors: int) -> bool:
    """A series with too many per-symbol request FAILURES this cycle is
    unusable: what did arrive is a biased (alphabetical-prefix) universe."""
    if attempts == 0:
        return False
    return errors / attempts <= _MAX_SERIES_ERROR_FRACTION


def _carry_signal(
    close: np.ndarray, funding: np.ndarray, volume: np.ndarray
) -> np.ndarray:
    from services.backtesting.funding_factors import trailing_mean

    return np.asarray(trailing_mean(funding, CARRY_LOOKBACK_STAMPS), dtype=float)


def _reversal_8h(
    close: np.ndarray, funding: np.ndarray, volume: np.ndarray
) -> np.ndarray:
    signal = np.full_like(close, np.nan, dtype=float)
    with np.errstate(invalid="ignore", divide="ignore"):
        signal[1:] = -(close[1:] / close[:-1] - 1.0)
    return signal


def _momentum_72h_fade(
    close: np.ndarray, funding: np.ndarray, volume: np.ndarray
) -> np.ndarray:
    signal = np.full_like(close, np.nan, dtype=float)
    with np.errstate(invalid="ignore", divide="ignore"):
        signal[9:] = -(close[9:] / close[:-9] - 1.0)
    return signal


def _low_vol_7d(
    close: np.ndarray, funding: np.ndarray, volume: np.ndarray
) -> np.ndarray:
    from services.backtesting.funding_factors import trailing_std

    returns = np.full_like(close, np.nan, dtype=float)
    with np.errstate(invalid="ignore", divide="ignore"):
        returns[1:] = close[1:] / close[:-1] - 1.0
    return -trailing_std(returns, 21)


def _momentum_24h_fade(
    close: np.ndarray, funding: np.ndarray, volume: np.ndarray
) -> np.ndarray:
    signal = np.full_like(close, np.nan, dtype=float)
    with np.errstate(invalid="ignore", divide="ignore"):
        signal[3:] = -(close[3:] / close[:-3] - 1.0)
    return signal


def _volume_surge_fade(
    close: np.ndarray, funding: np.ndarray, volume: np.ndarray
) -> np.ndarray:
    from services.backtesting.funding_factors import trailing_mean

    baseline = trailing_mean(volume, 21)
    with np.errstate(invalid="ignore", divide="ignore"):
        surge = np.where(baseline > 0, volume / baseline, np.nan)
    return np.asarray(-surge, dtype=float)


def _funding_delta_fade(
    close: np.ndarray, funding: np.ndarray, volume: np.ndarray
) -> np.ndarray:
    from services.backtesting.funding_factors import trailing_mean

    return np.asarray(-(funding - trailing_mean(funding, 21)), dtype=float)


def _oi_buildup_24h_fade(
    close: np.ndarray,
    funding: np.ndarray,
    volume: np.ndarray,
    extras: dict[str, np.ndarray],
) -> np.ndarray:
    """-(OI_t / OI_{t-3} - 1): fade the fastest 24h open-interest growth."""
    oi = extras["open_interest"]
    signal = np.full_like(close, np.nan, dtype=float)
    prev = oi[:-3]
    with np.errstate(invalid="ignore", divide="ignore"):
        signal[3:] = np.where(prev > 0, -(oi[3:] / prev - 1.0), np.nan)
    return signal


def _crowded_longs_fade(
    close: np.ndarray,
    funding: np.ndarray,
    volume: np.ndarray,
    extras: dict[str, np.ndarray],
) -> np.ndarray:
    """-globalLongShortAccountRatio_t: fade the account-count crowd."""
    return np.asarray(-extras["global_long_short"], dtype=float)


def _taker_buying_24h_fade(
    close: np.ndarray,
    funding: np.ndarray,
    volume: np.ndarray,
    extras: dict[str, np.ndarray],
) -> np.ndarray:
    """-mean(taker buy/sell ratio over the three stamps ending BEFORE t).

    The one-stamp lag is registered: the endpoint's stamping convention
    (period start vs end) is ambiguous, and the lag makes the signal causal
    under either convention at the cost of 8h of staleness.
    """
    from services.backtesting.funding_factors import trailing_mean

    taker = extras["taker_buy_ratio"]
    lagged = np.full_like(taker, np.nan, dtype=float)
    lagged[1:] = taker[:-1]
    return np.asarray(-trailing_mean(lagged, 3), dtype=float)


def _trend_follow_7d(
    close: np.ndarray, funding: np.ndarray, volume: np.ndarray
) -> np.ndarray:
    """+(close_t / close_{t-21} - 1): RIDE the 7-day trend -- the plus sign
    the systematic fortunes were made on (registered 2026-08-29)."""
    signal = np.full_like(close, np.nan, dtype=float)
    with np.errstate(invalid="ignore", divide="ignore"):
        signal[21:] = close[21:] / close[:-21] - 1.0
    return signal


def _trend_follow_30d(
    close: np.ndarray, funding: np.ndarray, volume: np.ndarray
) -> np.ndarray:
    """+(close_t / close_{t-90} - 1): the longest trend the grid carries;
    the documented edge lives at 3-12 months, and the registration says so."""
    signal = np.full_like(close, np.nan, dtype=float)
    with np.errstate(invalid="ignore", divide="ignore"):
        signal[90:] = close[90:] / close[:-90] - 1.0
    return signal


def _near_high_fade(
    close: np.ndarray, funding: np.ndarray, volume: np.ndarray
) -> np.ndarray:
    """-(close_t / rolling 21-stamp max of close): fade contracts AT their
    own ~7-day high. The kernel of the 2026-08-28 external claim, causal by
    construction (the max window ends at t).

    ALL 21 closes must be finite: nanmax over a NaN-padded window would
    shrink the registered statistic, and a freshly listed perp's first stamp
    would score exactly -1.0 -- the fade extreme -- regardless of price,
    feeding new-listing drift into the record as a fake positive IC
    (adversarial review, 2026-08-28). A shorter window is a different
    variable than the registered one, so it is absent, never approximated.
    """
    signal = np.full_like(close, np.nan, dtype=float)
    n = close.shape[0]
    import warnings

    with warnings.catch_warnings():
        warnings.simplefilter("ignore", RuntimeWarning)
        for t in range(n):
            lo = max(0, t - 20)
            window = close[lo : t + 1]
            high_water = np.nanmax(window, axis=0)
            full = np.isfinite(window).sum(axis=0) >= 21
            with np.errstate(invalid="ignore", divide="ignore"):
                signal[t] = np.where(
                    full & (high_water > 0), -(close[t] / high_water), np.nan
                )
    return signal


def _blend_registered_v1(
    close: np.ndarray, funding: np.ndarray, volume: np.ndarray
) -> np.ndarray:
    """Frozen equal-weight z-score blend of the four 2026-07/08 factors.

    Weights are equal and FROZEN at registration (cb700cc): re-weighting
    after seeing which component performs would be selection wearing a
    blend. A cell where every component is absent stays absent.
    """
    from services.backtesting.cross_section import cross_sectional_zscore

    components = [
        _carry_signal(close, funding, volume),
        _reversal_8h(close, funding, volume),
        _momentum_72h_fade(close, funding, volume),
        _low_vol_7d(close, funding, volume),
    ]
    stack = np.stack([cross_sectional_zscore(c) for c in components])
    import warnings

    with warnings.catch_warnings():
        warnings.simplefilter("ignore", RuntimeWarning)
        blend = np.nanmean(stack, axis=0)
    blend[np.all(~np.isfinite(stack), axis=0)] = np.nan
    return np.asarray(blend, dtype=float)


# The registry. Definitions, signs and boundaries are fixed by the
# pre-registrations in GO_LIVE.md (funding: 2026-07-31; batches on
# 2026-08-02, 2026-08-07 and 2026-08-09) and must not be edited after the
# fact -- the universe test pins them.
WATCHED_FACTORS: tuple[WatchedFactor, ...] = (
    WatchedFactor(FACTOR_NAME, UNSEEN_FROM, CARRY_LOOKBACK_STAMPS, _carry_signal),
    WatchedFactor(
        "reversal_8h_minus", datetime(2026, 8, 2, tzinfo=UTC), 2, _reversal_8h
    ),
    WatchedFactor(
        "momentum_72h_minus", datetime(2026, 8, 2, tzinfo=UTC), 10, _momentum_72h_fade
    ),
    WatchedFactor(
        "low_vol_7d_minus", datetime(2026, 8, 2, tzinfo=UTC), 22, _low_vol_7d
    ),
    WatchedFactor(
        "momentum_24h_minus", datetime(2026, 8, 7, tzinfo=UTC), 4, _momentum_24h_fade
    ),
    WatchedFactor(
        "volume_surge_minus", datetime(2026, 8, 7, tzinfo=UTC), 22, _volume_surge_fade
    ),
    WatchedFactor(
        "funding_delta_minus", datetime(2026, 8, 7, tzinfo=UTC), 22, _funding_delta_fade
    ),
    WatchedFactor(
        "blend_registered_v1", datetime(2026, 8, 7, tzinfo=UTC), 22, _blend_registered_v1
    ),
    WatchedFactor(
        "oi_buildup_24h_minus",
        datetime(2026, 8, 9, tzinfo=UTC),
        4,
        _oi_buildup_24h_fade,
        requires=("open_interest",),
    ),
    WatchedFactor(
        "crowded_longs_minus",
        datetime(2026, 8, 9, tzinfo=UTC),
        1,
        _crowded_longs_fade,
        requires=("global_long_short",),
    ),
    WatchedFactor(
        "taker_buying_24h_minus",
        datetime(2026, 8, 9, tzinfo=UTC),
        4,
        _taker_buying_24h_fade,
        requires=("taker_buy_ratio",),
    ),
    WatchedFactor(
        "near_high_fade_minus", datetime(2026, 8, 28, tzinfo=UTC), 22, _near_high_fade
    ),
    WatchedFactor(
        "trend_follow_7d_plus", datetime(2026, 8, 29, tzinfo=UTC), 22, _trend_follow_7d
    ),
    WatchedFactor(
        "trend_follow_30d_plus", datetime(2026, 8, 29, tzinfo=UTC), 91, _trend_follow_30d
    ),
)


def compute_signal_ics(
    times_ms: np.ndarray,
    close: np.ndarray,
    signal: np.ndarray,
    horizon: int,
    min_history: int = 1,
) -> list[tuple[int, float, int]]:
    """Generic core: [(stamp_ms, ic, n_symbols)] for any signal matrix.

    A stamp is resolvable when its forward window has fully closed and the
    signal has *min_history* stamps behind it. Outcome is the cross-
    sectionally demeaned forward return, so market direction cannot score.
    Spearman is rank-based, so signal builders need no normalisation.
    """
    from scipy import stats

    results: list[tuple[int, float, int]] = []
    n_periods = times_ms.size
    for t in range(min_history - 1, n_periods - horizon):
        row = signal[t]
        entry = close[t]
        exit_ = close[t + horizon]
        usable = np.isfinite(row) & np.isfinite(entry) & np.isfinite(exit_)
        if int(usable.sum()) < _MIN_SYMBOLS:
            continue
        forward = exit_[usable] / entry[usable] - 1.0
        forward = forward - forward.mean()
        sig = row[usable]
        if sig.std() == 0 or forward.std() == 0:
            continue
        rho = stats.spearmanr(sig, forward)
        if np.isnan(rho.statistic):
            continue
        results.append((int(times_ms[t]), float(rho.statistic), int(usable.sum())))
    return results


def compute_resolvable_ics(
    times_ms: np.ndarray,
    close: np.ndarray,
    funding: np.ndarray,
    horizon: int = HORIZON_STAMPS,
    lookback: int = CARRY_LOOKBACK_STAMPS,
) -> list[tuple[int, float, int]]:
    """Pure core: [(stamp_ms, ic, n_symbols)] for every resolvable stamp.

    A stamp is resolvable when its forward window has fully closed AND the
    factor has a full lookback behind it. The factor is +trailing-mean
    funding (high funding scored high -- the registered sign); the outcome is
    the cross-sectionally demeaned forward return, so market direction
    cannot score.
    """
    import warnings

    with warnings.catch_warnings():
        warnings.simplefilter("ignore", RuntimeWarning)
        carry = np.stack(
            [
                np.nanmean(funding[max(0, t - lookback + 1) : t + 1], axis=0)
                for t in range(times_ms.size)
            ]
        )
    # The lookback gate is enforced via min_history so partial windows at the
    # start are never scored, matching the original behaviour exactly.
    return compute_signal_ics(times_ms, close, carry, horizon, min_history=lookback)


def _fetch_recent(
    max_stamps: int = _FETCH_STAMPS,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, dict[str, np.ndarray]]:
    """Blocking fetch of recent 8h closes + per-8h funding for live perps,
    plus the registered extra series (OI, long/short, taker ratio).

    Runs in a worker thread. Uses only public endpoints; no keys involved.
    """
    import time

    import ccxt

    exchange = ccxt.binance({"options": {"defaultType": "future"}, "enableRateLimit": True})
    markets = exchange.load_markets()
    symbols = sorted(
        s for s, m in markets.items()
        if m.get("swap") and m.get("linear") and m.get("active")
        and m.get("quote") == "USDT"
    )

    # The data endpoints serve 4h periods (no 8h option); fetch enough 4h
    # points to compose every 8h stamp on the grid.
    extra_limit = min(500, (max_stamps + HORIZON_STAMPS) * 2 + 4)

    per_symbol_bars: dict[str, dict[int, tuple[float, float]]] = {}
    per_symbol_funding: dict[str, dict[int, float]] = {}
    per_symbol_extras: dict[str, dict[str, dict[int, float]]] = {
        name: {} for name in _EXTRA_SERIES
    }
    attempts = dict.fromkeys(_EXTRA_SERIES, 0)
    errors = dict.fromkeys(_EXTRA_SERIES, 0)
    # One closure decision for the whole cycle: the throttled loop takes
    # minutes, and a bar closing mid-loop must not be included for only the
    # late-alphabet symbols (a biased cross-section at that stamp).
    now_ms = int(time.time() * 1000)
    for symbol in symbols:
        try:
            bars = exchange.fetch_ohlcv(symbol, "8h", limit=max_stamps + HORIZON_STAMPS)
            history = exchange.fetch_funding_rate_history(
                symbol, limit=(max_stamps + CARRY_LOOKBACK_STAMPS) * 2
            )
        except Exception:
            continue  # one flaky symbol must not kill the cycle
        per_symbol_bars[symbol] = _closed_bars(bars, now_ms)
        rates: dict[int, float] = {}
        for row in history:
            stamp = (int(row["timestamp"]) // _MS_8H) * _MS_8H
            info = row.get("info") or {}
            # Normalise to per-8h: some contracts settle every 4 hours.
            interval = float(info.get("fundingIntervalHours") or 8.0)
            rates[stamp] = float(row["fundingRate"]) * (8.0 / max(interval, 1e-9))
        per_symbol_funding[symbol] = rates

        market_id = markets[symbol]["id"]
        for name, (method, parse) in _EXTRA_SERIES.items():
            time.sleep(_DATA_FAMILY_MIN_INTERVAL_S)  # the family's own IP cap
            attempts[name] += 1
            try:
                rows = getattr(exchange, method)(
                    {"symbol": market_id, "period": "4h", "limit": extra_limit}
                )
            except Exception:
                errors[name] += 1
                continue  # a missing series must not cost the symbol its bars
            aligned = parse(rows)
            if aligned:
                per_symbol_extras[name][symbol] = aligned

    for name in _EXTRA_SERIES:
        if not _series_is_trustworthy(attempts[name], errors[name]):
            logger.warning(
                "extra_series_degraded",
                series=name,
                attempts=attempts[name],
                errors=errors[name],
            )
            per_symbol_extras[name] = {}

    grid = np.array(
        sorted({s for bars in per_symbol_bars.values() for s in bars})[-max_stamps:],
        dtype=np.int64,
    )
    kept = sorted(per_symbol_bars)
    close = np.full((grid.size, len(kept)), np.nan)
    volume = np.full((grid.size, len(kept)), np.nan)
    funding = np.full((grid.size, len(kept)), np.nan)
    extras = {
        name: np.full((grid.size, len(kept)), np.nan) for name in _EXTRA_SERIES
    }
    index_of = {stamp: i for i, stamp in enumerate(grid)}
    for j, symbol in enumerate(kept):
        for stamp, (price, vol) in per_symbol_bars[symbol].items():
            i = index_of.get(stamp)
            if i is not None:
                close[i, j] = price
                volume[i, j] = vol
        rates = per_symbol_funding.get(symbol, {})
        last = np.nan
        for i, stamp in enumerate(grid):
            if stamp in rates:
                last = rates[stamp]
            if np.isfinite(close[i, j]):
                funding[i, j] = last
        for name in _EXTRA_SERIES:
            for stamp, value in per_symbol_extras[name].get(symbol, {}).items():
                i = index_of.get(stamp)
                if i is not None:
                    extras[name][i, j] = value
    _blank_ragged_retention_edge(extras)
    return grid, close, funding, volume, extras


class FundingWatchService:
    """Background loop persisting the live IC record."""

    def __init__(self, session_factory: async_sessionmaker[AsyncSession]) -> None:
        self._session_factory = session_factory
        self._task: asyncio.Task[None] | None = None

    async def start(self) -> None:
        self._task = asyncio.create_task(self._run())
        logger.info("FundingWatchService started.")

    async def stop(self) -> None:
        if self._task is not None:
            self._task.cancel()

    async def _run(self) -> None:
        while True:
            try:
                inserted = await self.observe_once()
                logger.info("funding_watch_cycle", new_observations=inserted)
            except asyncio.CancelledError:
                break
            except Exception:
                logger.exception("funding_watch_cycle_failed")
            await asyncio.sleep(_CYCLE_SECONDS)

    async def observe_once(self) -> int:
        """Fetch once, then resolve and insert for EVERY registered factor."""
        grid, close, funding, volume, extras = await asyncio.to_thread(_fetch_recent)
        if grid.size == 0:
            return 0

        inserted = 0
        async with self._session_factory() as session:
            now = datetime.now(UTC)
            for factor in WATCHED_FACTORS:
                if factor.requires:
                    missing = [
                        key
                        for key in factor.requires
                        if key not in extras or not np.isfinite(extras[key]).any()
                    ]
                    if missing:
                        # Skipped, never fed garbage: an absent series must
                        # surface as a missing observation, not a wrong one.
                        logger.warning(
                            "factor_series_missing",
                            factor=factor.name,
                            missing=missing,
                        )
                        continue
                    signal = factor.build(close, funding, volume, extras)  # type: ignore[call-arg]
                else:
                    signal = factor.build(close, funding, volume)  # type: ignore[call-arg]
                candidates = compute_signal_ics(
                    grid, close, signal, HORIZON_STAMPS, factor.min_history
                )
                if not candidates:
                    continue
                existing = await self._existing_stamps(session, factor.name)
                for stamp_ms, ic, n_symbols in candidates:
                    when = datetime.fromtimestamp(stamp_ms / 1000, UTC)
                    if when < factor.unseen_from or when in existing:
                        continue
                    if (now - when).total_seconds() > _MAX_HEAL_DAYS * 86_400:
                        # A stamp this stale would be scored on TODAY's
                        # listing set: a visible gap beats a survivorship-
                        # tinted row (review, 2026-08-29).
                        continue
                    session.add(
                        FactorWatchObservation(
                            time=when,
                            factor=factor.name,
                            horizon_stamps=HORIZON_STAMPS,
                            ic=ic,
                            n_symbols=n_symbols,
                            resolved_at=now,
                        )
                    )
                    inserted += 1
            if inserted:
                await session.commit()
        return inserted

    async def _existing_stamps(
        self, session: AsyncSession, factor: str = FACTOR_NAME
    ) -> set[datetime]:
        result = await session.execute(
            select(FactorWatchObservation.time).where(
                FactorWatchObservation.factor == factor
            )
        )
        return {row[0].replace(tzinfo=UTC) if row[0].tzinfo is None else row[0]
                for row in result.all()}


def quarterly_rollup(
    observations: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Aggregate stamp ICs into calendar quarters for the adjudication view."""
    buckets: dict[str, list[float]] = {}
    for obs in observations:
        when: datetime = obs["time"]
        quarter = f"{when.year}-Q{(when.month - 1) // 3 + 1}"
        buckets.setdefault(quarter, []).append(float(obs["ic"]))
    rollup: list[dict[str, Any]] = []
    for quarter in sorted(buckets):
        values = np.array(buckets[quarter])
        mean = float(values.mean())
        std = float(values.std(ddof=1)) if values.size > 1 else 0.0
        t_stat = float(mean / std * np.sqrt(values.size)) if std > 0 else 0.0
        rollup.append(
            {
                "quarter": quarter,
                "n": int(values.size),
                "mean_ic": mean,
                "t_stat": t_stat,
                "positive": mean > 0,
            }
        )
    return rollup
