"""factor_watch -- append-only walk-forward adjudication record

Revision ID: 0008_factor_watch
Revises: 0007_positions_mode
Create Date: 2026-07-31

PR #64 parked a regime hypothesis ("since mid-2025, high-funding perpetual
contracts outperform") that was generated by historical data and therefore
can only be adjudicated by FUTURE data. This table is the adjudication
record: one immutable row per (factor, 8h stamp) holding the live
cross-sectional IC, inserted when the stamp's forward window closes and
never recomputed -- recomputation from a later listing set would
reintroduce survivorship bias into the record itself.

Guarded with has_table because 0001 creates the whole ORM schema via
``metadata.create_all`` on fresh databases.
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = "0008_factor_watch"
down_revision = "0007_positions_mode"
branch_labels = None
depends_on = None

_TABLE = "factor_watch"


def upgrade() -> None:
    if sa.inspect(op.get_bind()).has_table(_TABLE):
        return
    op.create_table(
        _TABLE,
        sa.Column("time", sa.DateTime(timezone=True), primary_key=True, nullable=False),
        sa.Column("factor", sa.String(60), primary_key=True, nullable=False),
        sa.Column("horizon_stamps", sa.Integer, nullable=False),
        sa.Column("ic", sa.Float, nullable=False),
        sa.Column("n_symbols", sa.Integer, nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=False),
    )


def downgrade() -> None:
    if sa.inspect(op.get_bind()).has_table(_TABLE):
        op.drop_table(_TABLE)
