"""Walk-forward research endpoints.

Read-only view over the ``factor_watch`` adjudication record: the live
quarterly IC of the registered funding-regime hypothesis, and how far it is
through the registered bar (four consecutive positive quarters on unseen
data). The API reports; it does not judge early.
"""

from __future__ import annotations

from typing import Any

from fastapi import APIRouter, Depends
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from api.dependencies import get_current_user, get_db
from core.models.research import FactorWatchObservation
from services.research.funding_watch import (
    FACTOR_NAME,
    HORIZON_STAMPS,
    UNSEEN_FROM,
    quarterly_rollup,
)

router = APIRouter(prefix="/research")

# The registered bar, restated where the API serves it so the UI cannot
# drift from the runbook.
REQUIRED_CONSECUTIVE_POSITIVE_QUARTERS = 4


@router.get(
    "/funding-watch",
    summary="Live walk-forward record of the registered funding-regime hypothesis",
)
async def get_funding_watch(
    db: AsyncSession = Depends(get_db),
    _user: dict[str, Any] = Depends(get_current_user),
) -> dict[str, Any]:
    result = await db.execute(
        select(FactorWatchObservation)
        .where(FactorWatchObservation.factor == FACTOR_NAME)
        .order_by(FactorWatchObservation.time)
    )
    rows = result.scalars().all()
    observations = [
        {"time": row.time, "ic": row.ic, "n_symbols": row.n_symbols}
        for row in rows
    ]
    quarters = quarterly_rollup(observations)

    # Consecutive positive quarters, counted from the most recent backwards.
    # Only COMPLETE adjudication can end the watch, so the current (partial)
    # quarter is reported but flagged.
    streak = 0
    for q in reversed(quarters):
        if q["positive"]:
            streak += 1
        else:
            break

    return {
        "factor": FACTOR_NAME,
        "hypothesis": (
            "Since mid-2025, perpetual contracts with HIGH funding outperform "
            "cross-sectionally (registered GO_LIVE.md 2026-07-31; generated by "
            "historical data, adjudicable only by data after "
            f"{UNSEEN_FROM.date().isoformat()})"
        ),
        "horizon_hours": HORIZON_STAMPS * 8,
        "unseen_from": UNSEEN_FROM,
        "required_consecutive_positive_quarters": REQUIRED_CONSECUTIVE_POSITIVE_QUARTERS,
        "observations_recorded": len(observations),
        "quarters": [
            {
                "quarter": q["quarter"],
                "n": q["n"],
                "mean_ic": round(q["mean_ic"], 5),
                "t_stat": round(q["t_stat"], 2),
                "positive": q["positive"],
            }
            for q in quarters
        ],
        "current_positive_streak": streak,
        "verdict": (
            "watching -- no trading proposal may cite this factor until the "
            "registered bar is met on complete quarters"
        ),
    }
